# Generated by Django 2.2.3 on 2019-11-15 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('call', models.CharField(max_length=15)),
                ('access', models.CharField(max_length=3)),
                ('parking', models.CharField(max_length=3)),
                ('height', models.CharField(max_length=3)),
                ('lift', models.CharField(max_length=3)),
                ('toilet', models.CharField(max_length=3)),
                ('customRoom', models.CharField(max_length=3)),
                ('seat', models.CharField(max_length=3)),
                ('ticket', models.CharField(max_length=3)),
                ('blindConve', models.CharField(max_length=3)),
                ('deafConve', models.CharField(max_length=3)),
                ('guidance', models.CharField(max_length=3)),
                ('wheelchair', models.CharField(max_length=3)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('call', models.CharField(max_length=15)),
                ('access', models.CharField(max_length=3)),
                ('parking', models.CharField(max_length=3)),
                ('height', models.CharField(max_length=3)),
                ('lift', models.CharField(max_length=3)),
                ('toilet', models.CharField(max_length=3)),
                ('customRoom', models.CharField(max_length=3)),
                ('seat', models.CharField(max_length=3)),
                ('ticket', models.CharField(max_length=3)),
                ('blindConve', models.CharField(max_length=3)),
                ('deafConve', models.CharField(max_length=3)),
                ('guidance', models.CharField(max_length=3)),
                ('wheelchair', models.CharField(max_length=3)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
