# Generated by Django 2.2.3 on 2019-11-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystorage', '0002_auto_20191115_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='latitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='longitude',
            field=models.CharField(max_length=100),
        ),
    ]
